name: "Zip and Upload to NekoWeb"

inputs:
  nekoweb-api-key:
    description: "Your NekoWeb API key."
    required: true
  nekoweb-domain:
    description: "Your NekoWeb domain to deploy to."
    required: true
  nekoweb-username:
    description: "Your NekoWeb username."
    required: true
  ignore-paths:
    description: "Comma-separated list of folders/files to exclude from ZIP"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: actions/setup-node@v4

    - name: Download Deployment Script
      run: git clone --depth 1 https://github.com/Pufikas/deploytonekoweb.git
      shell: bash

    - name: Clone website repo into site/
      working-directory: deploytonekoweb
      run: git clone --depth 1 https://github.com/${{ github.repository }} site
      shell: bash

    - name: Install Dependencies
      working-directory: deploytonekoweb
      run: npm ci
      shell: bash

    - name: Deploy
      working-directory: deploytonekoweb
      env:
          APIKEY: ${{ inputs.nekoweb-api-key }}
          DOMAIN: ${{ inputs.nekoweb-domain }}
          USERNAME: ${{ inputs.nekoweb-username }}
          IGNORE_PATHS: ${{ inputs.ignore-paths }}
      run: npm run deploy
      shell: bash
